controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

kernel:
    resource: ../src/Kernel.php
    type: attribute

api_login_check:
    path: /api/login
    